import { storyKeyFromUrl } from "../runtime/urlMode.js";
import { audioCueView } from "../audioCatalog.js";
import { dailyAccusationChoices } from "../dailyChoices.js";
import { materialOperationOutcome } from "../runtime/materialOperation.js";
import { askedDialoguePicksForState, completedSceneExchangeForState, contradictionsForState, latestChoiceReviewRowsForState, routeAxisProfileForState, routeChoicesForState, selectedDelegationPickForState, selectedEvidencePickForState, selectedEvidencePicksForState, selectedInvestigationPickForState, selectedInvestigationPicksForState, selectedScenePickForState, truthBoundaryMissesForState, truthBoundaryPicksForState, unlockedInvestigationEntriesForState } from "../runtime/caseStateSelectors.js";
import { finalQuoteComparison, investigationPickReaction, issueLine, issueResultLine, recapRankLabel, truthBoundaryAftertaste, truthBoundaryReview } from "../runtime/recapModel.js";
import { materialPressureReaction, materialPressureSignal, pressuredAnswerVariant, questionPressureReaction, questionPressureSignal } from "../runtime/livePressure.js";
import { routeAxisForChoice, routeToneForChoice } from "../runtime/routeLog.js";
import { afterEvidenceScene as nextSceneAfterEvidence, afterSceneEvidenceFor, answerKey, availableCallbackOpeners, availableOvernightCallbackOpeners, callbackOpenerById, canEnterOvernightCallback, caseKey, daySceneById, delegationFor, delegationOutcomeFor, delegationRouteAxisForAdvisor, documentById, documentRowById, earnedDocumentQuestionsFor, evidenceAnswerKey, evidenceCheckModel, evidenceChecksFor, interludeEarnedItemsForOvernight, investigationAnswerKey, investigationBackflowModel, investigationRouteIndexBase, keyQuestionLimit, liveCounterBeatAfterScene, liveCounterBeatBeforeScene, liveCounterBeatById, liveCounterBeatsFor, nextPlayableSceneIndex, nightActionById, nightStructureFor, overnightCallbackDialogueLines, overnightCallbackOpenerById, overnightCallerQuestionFor, overnightFirstNight2SceneIndex, overnightReturnPostureFor, overnightStructureFor, playableSceneIndexes, pressureSignalForLiveCounterChoice, returnStanceFor, sceneReviewModel, shouldEnterHangupAfterScene, shouldEnterOvernightHangupAfterScene, snapshotEchoFor, stanceSnapshotForScene } from "../runtime/sceneAdvance.js";
import { storyInterludeCaseId, storyOptionalQuickCall } from "../runtime/storyInterludeModel.js";
import { careChoiceById, careChoicesFor } from "../runtime/careChoiceModel.js";
import { epilogueUnreadStage } from "../runtime/epilogueUnreadModel.js";
import { cafePrologueCanOpenForensic, cafePrologueCanPresentEvidence, cafePrologueCanPresentRevisionEvidence, cafePrologueRemainingEvidenceId, cafePrologueRevisionEvidenceHit, cafePrologueRevisedStatementReady, cafePrologueSceneForStep, cafePrologueStatementReady, normalizedCafePrologueProgress } from "../runtime/prologueCafeModel.js";
import { hostDisclosureLinesForAnchor } from "../runtime/hostDisclosureModel.js";
import { CHOICE_COST_META } from "../runtime/choiceCostModel.js";
import { storyPressureRows } from "../runtime/storyPackSummaryModel.js";
import { callDialogueHtml, choiceButtonBodyHtml, choiceGroupHtml, choiceReviewHtml, flowGroupHtml } from "./callFlowView.js";
import { dailyCompleteChoicesHtml, dailyCompleteHtml, dailyCompleteShareText } from "./dailyCompleteView.js";
import { delegationScreenHtml, evidenceCheckScreenHtml, investigationBackflowScreenHtml } from "./evidenceView.js";
import { audioPlaybackControlsHtml, callbackOpenerBeatHtml, callbackOpenerChoiceHtml, hangupBeatHtml, interludeDeskHtml, interludeDialogueActionHtml, interludePlaybackActionHtml, interruptToastHtml, replyChoicesHtml } from "./interludeDeskView.js";
import { liveCounterBeatHtml } from "./liveCounterBeatView.js";
import { finalQuoteComparisonHtml, solvedRecapFlowView, solvedRecapPagesHtml } from "./recapView.js";
import { routeTrailHtml } from "./routeTrailView.js";
import { focusedQuestionOptions, sceneDialogueOptions, sceneQuestionChoicesHtml } from "./sceneQuestions.js";
import { completedSceneExchangeHtml, scenePromptExchangeHtml, sceneQuestionAnswerHtml, sceneReviewDoneChoicesHtml, sceneReviewHtml, stanceSnapshotHtml, statementStagePromptExchangeHtml } from "./sceneReviewView.js";
import { storyInterludeChoicesHtml, storyInterludeHtml, storyInterludeStageHtml, storyWorldEchoStageHtml } from "./storyInterludeView.js";
import { caseBridgeChoicesHtml, caseBridgeHtml, caseClosingChoicesHtml, caseClosingHtml, caseTitleChoicesHtml, caseTitleHtml } from "./caseTransitionView.js";
import { careChoiceContinueHtml, careChoiceHtml } from "./careChoiceView.js";
import { epilogueUnreadContinueHtml, epilogueUnreadHtml } from "./epilogueUnreadView.js";
import { cafeAccountBoardHtml, cafeEvidencePairHtml, cafeFinalBoundaryHtml, cafeInvestigationChoicesHtml, cafeLegalRequestsHtml, cafeMaterialDetailModalHtml, cafeMaterialPromptHtml, cafePrologueDialogueHtml, cafePrologueHeaderHtml, cafeProloguePortraitStageHtml, cafeRevisionStatusHtml, cafeSingleEvidenceHtml, cafeStatementReplayHtml, cafeTransferPresentHtml } from "./prologueCafeView.js";
import { storyPackCompleteHtml } from "./storyPackCompleteView.js";
import { CONTENT_ADVISORS } from "../generated/contentPackIndex.js";
import { storyPackForKey } from "../storyPacks.js";

export function createDailyQueryView(bound) {
  const queries = {
    availableCallbackOpeners,
    availableOvernightCallbackOpeners,
    callbackOpenerById,
    canEnterOvernightCallback,
    caseKey,
    daySceneById,
    documentById,
    documentRowById,
    earnedDocumentQuestionsFor,
    evidenceChecksFor,
    keyQuestionLimit,
    liveCounterBeatAfterScene,
    liveCounterBeatBeforeScene,
    liveCounterBeatById,
    pressureSignalForLiveCounterChoice,
    nextPlayableSceneIndex,
    nightStructureFor,
    overnightCallbackDialogueLines,
    overnightCallbackOpenerById,
    overnightFirstNight2SceneIndex,
    overnightReturnPostureFor,
    overnightStructureFor,
    playableSceneIndexes,
    returnStanceFor,
    snapshotEchoFor,
    CHOICE_COST_META,
    stanceSnapshotPickForState: bound.stanceSnapshotPickForState,
    currentIndex: bound.currentIndex,
    sceneAfterEvidenceFor: bound.sceneAfterEvidenceFor,
    materialOperationOutcome,
    latestChoiceReviewRowsForState,
    selectedDelegationPickForState,
    selectedEvidencePickForState,
    selectedInvestigationPickForState,
    unlockedInvestigationEntriesForState,
    investigationPickReaction,
    materialPressureReaction,
    materialPressureSignal,
    afterSceneEvidenceFor,
    answerKey,
    delegationFor,
    delegationOutcomeFor,
    delegationRouteAxisForAdvisor,
    evidenceAnswerKey,
    evidenceCheckModel,
    interludeEarnedItemsForOvernight,
    investigationAnswerKey,
    investigationBackflowModel,
    investigationRouteIndexBase,
    nightActionById,
    shouldEnterHangupAfterScene,
    shouldEnterOvernightHangupAfterScene,
    CONTENT_ADVISORS,
    issueCompletion: bound.issueCompletion,
    interludeActionState: bound.interludeActionState,
    countCompletedInterludeActions: bound.countCompletedInterludeActions,
    hasDeepFollowup: bound.hasDeepFollowup,
    materialPityLineFor: bound.materialPityLineFor,
    dailyAccusationChoices,
    askedDialoguePicksForState,
    completedSceneExchangeForState,
    selectedScenePickForState,
    pressuredAnswerVariant,
    questionPressureReaction,
    questionPressureSignal,
    routeAxisForChoice,
    routeToneForChoice,
    nextSceneAfterEvidence,
    overnightCallerQuestionFor,
    sceneReviewModel,
    stanceSnapshotForScene,
    focusedQuestionOptions,
    sceneDialogueOptions,
    sceneWithShownCard: bound.sceneWithShownCard,
    sceneWithCallbackRevision: bound.sceneWithCallbackRevision,
    sceneRevisionUnlocked: bound.sceneRevisionUnlocked,
    firstUnansweredSceneIndex: bound.firstPendingSceneIndex,
    resolveAccusationFromButton: bound.resolveAccusationFromButton,
    accusationReadinessForBrief: bound.accusationReadinessForBrief,
    retryPatienceLostStep: bound.retryPatienceLostStep,
    audiencePatienceLost: bound.audiencePatienceLost,
    deepFollowupFor: bound.deepFollowupFor,
    contradictionsForState,
    routeAxisProfileForState,
    routeChoicesForState,
    selectedEvidencePicksForState,
    selectedInvestigationPicksForState,
    truthBoundaryMissesForState,
    truthBoundaryPicksForState,
    finalQuoteComparison,
    issueLine,
    issueResultLine,
    recapRankLabel,
    truthBoundaryAftertaste,
    truthBoundaryReview,
    liveCounterBeatsFor,
    storyInterludeCaseId,
    storyOptionalQuickCall,
    careChoiceById,
    careChoicesFor,
    epilogueUnreadStage,
    normalizedCafePrologueProgress,
    cafePrologueStatementReady,
    cafePrologueCanPresentEvidence,
    cafePrologueRevisedStatementReady,
    cafePrologueCanPresentRevisionEvidence,
    cafePrologueRevisionEvidenceHit,
    cafePrologueRemainingEvidenceId,
    cafePrologueCanOpenForensic,
    cafePrologueSceneForStep,
    hostDisclosureLinesForAnchor,
    storyPressureRows,
    dailyCompleteShareText,
    storyPackForKey,
    isStoryPackMode: bound.isStoryPackMode,
    storyKeyFromUrl,
    nightShellForBrief: bound.nightShellForBrief,
    nightShellInterludeForBrief: bound.nightShellInterludeForBrief,
    nightShellGoodEnding: bound.nightShellGoodEnding,
    nightShellEndingKey: bound.nightShellEndingKey,
    normalizedDailyResult: bound.normalizedDailyResult,
    routeProfileForBrief: bound.routeProfileForBrief,
    postDailySharePayload: bound.postDailySharePayload,
    dailyConclusion: bound.dailyConclusion,
    liveCounterPickKey: bound.liveCounterPickKey,
    liveCounterPickForState: bound.liveCounterPickForState,
  };
  const view = {
    audioCueView,
    callDialogueHtml,
    choiceButtonBodyHtml,
    flowGroupHtml,
    audioPlaybackControlsHtml,
    callbackOpenerBeatHtml,
    callbackOpenerChoiceHtml,
    liveCounterBeatHtml,
    frame: bound.frame,
    dayFrame: bound.dayFrame,
    hostPortraitLayer: bound.hostPortraitLayer,
    liveCommentStrip: bound.liveCommentStrip,
    escapeHtml: bound.appEscapeHtml,
    choiceReviewHtml,
    delegationScreenHtml,
    evidenceCheckScreenHtml,
    investigationBackflowScreenHtml,
    interludeDeskHtml,
    interludeDialogueActionHtml,
    interludePlaybackActionHtml,
    interruptToastHtml,
    replyChoicesHtml,
    liveChapterTitle: bound.liveChapterTitle,
    choiceGroupHtml,
    hangupBeatHtml,
    sceneQuestionChoicesHtml,
    completedSceneExchangeHtml,
    scenePromptExchangeHtml,
    statementStagePromptExchangeHtml,
    sceneQuestionAnswerHtml,
    sceneReviewDoneChoicesHtml,
    sceneReviewHtml,
    stanceSnapshotHtml,
    dailyCompleteChoicesHtml,
    dailyCompleteHtml,
    finalQuoteComparisonHtml,
    solvedRecapFlowView,
    solvedRecapPagesHtml,
    routeTrailHtml,
    storyInterludeChoicesHtml,
    storyInterludeHtml,
    storyInterludeStageHtml,
    storyWorldEchoStageHtml,
    caseBridgeChoicesHtml,
    caseBridgeHtml,
    caseClosingChoicesHtml,
    caseClosingHtml,
    caseTitleChoicesHtml,
    caseTitleHtml,
    careChoiceContinueHtml,
    careChoiceHtml,
    epilogueUnreadContinueHtml,
    epilogueUnreadHtml,
    cafePrologueHeaderHtml,
    cafePrologueDialogueHtml,
    cafeProloguePortraitStageHtml,
    cafeRevisionStatusHtml,
    cafeMaterialDetailModalHtml,
    cafeMaterialPromptHtml,
    cafeStatementReplayHtml,
    cafeEvidencePairHtml,
    cafeSingleEvidenceHtml,
    cafeTransferPresentHtml,
    cafeLegalRequestsHtml,
    cafeInvestigationChoicesHtml,
    cafeAccountBoardHtml,
    cafeFinalBoundaryHtml,
    storyPackCompleteHtml,
    compactDialogueLines: bound.compactDialogueLines,
    hostDisclosureForAnchor: (...args) => bound.screens.hostDisclosureForAnchor(...args),
    respondentTeaseHtml: (...args) => bound.screens.respondentTeaseHtml(...args),
  };
  return { queries, view };
}
